const userSchema = `CREATE TABLE P_USER (
    USER_ID INTEGER AUTO_INCREMENT NOT NULL,
    USERNAME VARCHAR(100),
    USER_EMAIL VARCHAR(100),
    USER_PASSWORD VARCHAR(300),
    PRIMARY KEY (USER_ID)
);`;
const languageSchema = `CREATE TABLE P_LANGUAGE (
    LANGUAGE_ID INTEGER AUTO_INCREMENT NOT NULL,
    LANGUAGE_NAME VARCHAR(12) NOT NULL UNIQUE,
    LANGUAGE_SANDBOX VARCHAR(20) NOT NULL UNIQUE,
    PRIMARY KEY (LANGUAGE_ID)
);`;
const problemSchema = `CREATE TABLE P_PROBLEM (
    PROBLEM_ID INTEGER AUTO_INCREMENT NOT NULL,
    PROBLEM_NAME VARCHAR(40) NOT NULL UNIQUE,
    PROBLEM_DESCRIPTION TEXT NOT NULL,
    PROBLEM_TESTCASE MEDIUMTEXT,
    PROBLEM_TIMEOUT INTEGER NOT NULL,
    PROBLEM_DIFFICULTY ENUM('EASY', 'MEDIUM', 'HARD'),
    PROBLEM_ACCEPTANCE INTEGER,
    PROBLEM_TEMPLATE TEXT,
    PRIMARY KEY (PROBLEM_ID)
);`;
const submissionSchema = `CREATE TABLE P_SUBMISSION (
    SUBMISSION_ID INTEGER AUTO_INCREMENT NOT NULL,
    SUBMISSION TEXT NOT NULL,
    SUBMISSION_LANG_ID VARCHAR(5) NOT NULL,
    SUBMISSION_STATUS ENUM('ACCEPTED', 'REJECTED'),
    SUBMISSION_PROBLEM_ID VARCHAR(8) NOT NULL, 
    SUBMISSION_RESULT TEXT,
    SUBMISSION_USER_ID INTEGER NOT NULL,
    PRIMARY KEY (SUBMISSION_ID),
    FOREIGN KEY (SUBMISSION_PROBLEM_ID) REFERENCES P_PROBLEM(PROBLEM_ID),
    FOREIGN KEY (SUBMISSION_USER_ID) REFERENCES P_USER(USER_ID),
    FOREIGN KEY (SUBMISSION_LANG_ID) REFERENCES P_LANGUAGE(LANGUAGE_ID)
);`;
module.exports = {
  userSchema: userSchema,
  languageSchema: languageSchema,
  problemSchema: problemSchema,
  submissionSchema: submissionSchema,
};
